name: Build and Commit PDFs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-belegarbeit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          working_directory: belegarbeit
          root_file: main.tex
          latexmk_shell_escape: true
          extra_system_packages: "inkscape"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: belegarbeit
          path: belegarbeit/main.pdf

  build-presentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: presentation.tex
          working_directory: presentation
          latexmk_shell_escape: true
          extra_system_packages: "inkscape"
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: presentation
          path: presentation/presentation.pdf

  commit-documents:
    needs: [build-belegarbeit, build-presentation]
    runs-on: ubuntu-latest
    steps:
      - name: Download belegarbeit artifact
        uses: actions/download-artifact@v3
        with:
          name: belegarbeit
      - name: Download presentation artifact
        uses: actions/download-artifact@v3
        with:
          name: presentation

      - name: Clone target repository
        run: |
          git clone https://${{ secrets.PAT }}@github.com/beleg-05-resilienz-verteilte-systeme/Abgabe.git target_repo
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Copy built PDF to target repository
        run: |
          cp main.pdf target_repo/05-resilienz-verteilte-systeme.pdf
          cp presentation.pdf target_repo/05-folien-resilienz-verteilte-systeme.pdf

      - name: Commit and push to target repository
        run: |
          cd target_repo
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update PDFs"
          git push origin main
